# Generated by Django 5.0.2 on 2024-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('sector', models.IntegerField()),
                ('fuelburn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuelperseat', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
