# Generated by Django 5.0.2 on 2024-04-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0007_fleet_cycles_fleet_last_100_hour_inspection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='last_a_check',
            new_name='next_a_check',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='last_b_check',
            new_name='next_b_check',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='last_c_check',
            new_name='next_c_check',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='last_100_hour_inspection',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='last_engine_overhaul',
        ),
    ]
