# Generated by Django 5.0.2 on 2024-04-15 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0008_rename_last_a_check_fleet_next_a_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='next_d_check',
            field=models.DateField(default=datetime.date(2031, 12, 15)),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_a_check',
            field=models.DateField(default=datetime.date(2024, 6, 24)),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_b_check',
            field=models.DateField(default=datetime.date(2025, 1, 20)),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_c_check',
            field=models.DateField(default=datetime.date(2025, 10, 27)),
        ),
    ]
