# Generated by Django 5.0.2 on 2024-04-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0010_aircraft_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='livery',
            field=models.ImageField(default='default.png', upload_to='fleet_images/'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.ImageField(default='default.png', upload_to='aircraft_images/'),
        ),
    ]
