# Generated by Django 5.0.2 on 2024-04-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0011_fleet_livery_alter_aircraft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.ImageField(default='aircraft_images/default.png', upload_to='aircraft_images/'),
        ),
    ]
