# Generated by Django 5.0.2 on 2024-04-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0012_alter_aircraft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.ImageField(default='default.png', upload_to='airline_app/aircraft_images/'),
        ),
    ]
