# Generated by Django 5.0.2 on 2024-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0014_alter_aircraft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='livery',
            field=models.ImageField(default='default.png', upload_to='livery_images/'),
        ),
    ]
