# Generated by Django 5.0.2 on 2024-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0015_alter_fleet_livery'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='livery_title',
            field=models.CharField(default='Factory finish', max_length=32),
        ),
    ]
