# Generated by Django 5.0.2 on 2024-04-16 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0016_fleet_livery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=3)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.IntegerField()),
                ('arrival_delay', models.IntegerField()),
                ('departure_delay', models.IntegerField()),
                ('timezone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_a_check',
            field=models.DateField(default=datetime.date(2024, 6, 25)),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_b_check',
            field=models.DateField(default=datetime.date(2025, 1, 21)),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_c_check',
            field=models.DateField(default=datetime.date(2025, 10, 28)),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_d_check',
            field=models.DateField(default=datetime.date(2031, 12, 16)),
        ),
    ]
