# Generated by Django 5.0.2 on 2024-04-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0017_airport_alter_fleet_next_a_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
