# Generated by Django 5.0.2 on 2024-04-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0020_airline_customer_rating_alter_airport_arrival_delay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='fuelburn',
            new_name='fuel_burn',
        ),
    ]
