# Generated by Django 5.0.2 on 2024-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0023_aircraft_price_millions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='price_millions',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
    ]
