# Generated by Django 5.0.2 on 2024-04-17 13:38


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0024_alter_aircraft_price_millions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='sector',
            new_name='range',
        ),
    ]
