# Generated by Django 5.0.2 on 2024-04-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0025_rename_sector_aircraft_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_designator', models.CharField(blank=True, max_length=2)),
                ('airline', models.ForeignKey(default='XX XXXX', on_delete=django.db.models.deletion.CASCADE, to='airline_app.airline')),
            ],
        ),
    ]
