# Generated by Django 5.0.2 on 2024-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0026_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline_designator',
        ),
        migrations.AddField(
            model_name='flight',
            name='number',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
