# Generated by Django 5.0.2 on 2024-04-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0032_alter_flight_aircraft_alter_flight_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='number',
        ),
    ]
