# Generated by Django 5.0.2 on 2024-04-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0034_remove_flight_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(default=1, limit_choices_to={'airline': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airline_app.airline')}, on_delete=django.db.models.deletion.CASCADE, to='airline_app.fleet'),
            preserve_default=False,
        ),
    ]
