# Generated by Django 5.0.2 on 2024-04-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0035_flight_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(limit_choices_to={'id': models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airline_app.airline')}, on_delete=django.db.models.deletion.CASCADE, to='airline_app.fleet'),
        ),
    ]
