# Generated by Django 5.0.2 on 2024-04-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0036_flight_number_alter_flight_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(limit_choices_to={'airline': 1}, on_delete=django.db.models.deletion.CASCADE, to='airline_app.fleet'),
        ),
    ]
