# Generated by Django 5.0.2 on 2024-04-17 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0038_alter_flight_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airline_app.airport'),
            preserve_default=False,
        ),
    ]
