# Generated by Django 5.0.2 on 2024-04-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0039_flight_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='act_arrival_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='act_departure_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_choices', to='airline_app.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='flight',
            name='sch_arrival_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='sch_departure_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_choices', to='airline_app.airport'),
        ),
    ]
