# Generated by Django 5.0.2 on 2024-04-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0040_flight_act_arrival_time_flight_act_departure_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='sch_departure_time',
            new_name='departure_sch_time',
        ),
        migrations.AlterField(
            model_name='flight',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
