# Generated by Django 5.0.2 on 2024-04-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0041_rename_sch_departure_time_flight_departure_sch_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='departure_sch_time',
        ),
        migrations.AddField(
            model_name='flight',
            name='sch_departure',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
