# Generated by Django 5.0.2 on 2024-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0042_remove_flight_departure_sch_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='sch_departure',
        ),
        migrations.AddField(
            model_name='flight',
            name='sch_departure_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='act_arrival_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='act_departure_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sch_arrival_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
