# Generated by Django 5.0.2 on 2024-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0043_remove_flight_sch_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
