# Generated by Django 5.0.2 on 2024-04-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0044_flight_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=0.75, max_digits=4),
        ),
        migrations.AlterField(
            model_name='flight',
            name='act_arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='act_departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sch_arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sch_departure_time',
            field=models.TimeField(),
        ),
    ]
