# Generated by Django 5.0.2 on 2024-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0046_flight_distance_alter_fleet_next_a_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='next_a_check',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_b_check',
            field=models.PositiveIntegerField(default=280),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_c_check',
            field=models.PositiveIntegerField(default=560),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_d_check',
            field=models.PositiveIntegerField(default=2800),
        ),
    ]
