# Generated by Django 5.0.2 on 2024-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0047_alter_fleet_next_a_check_alter_fleet_next_b_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
