# Generated by Django 5.0.2 on 2024-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0048_flight_tickets_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_price', models.DecimalField(decimal_places=6, default=0.07604, max_digits=10)),
            ],
        ),
    ]
