# Generated by Django 5.0.2 on 2024-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0049_economy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
