# Generated by Django 5.0.2 on 2024-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0050_simengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='rating',
            field=models.DecimalField(decimal_places=3, default=0.75, max_digits=4),
        ),
    ]
