# Generated by Django 5.0.2 on 2024-04-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0053_remove_airline_customer_rating_airline_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='model',
            new_name='aircraft',
        ),
    ]
