# Generated by Django 5.0.2 on 2024-04-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0054_rename_model_fleet_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='fuel_burn',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fuel burn (lbs/hr)'),
        ),
    ]
