# Generated by Django 5.0.2 on 2024-04-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0055_alter_aircraft_fuel_burn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='cruise_speed',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Cruise speed (mph)'),
        ),
    ]
