# Generated by Django 5.0.2 on 2024-04-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0057_remove_aircraft_fuel_per_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simengine',
            old_name='day',
            new_name='sim_day',
        ),
    ]
