# Generated by Django 5.0.2 on 2024-04-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0058_rename_day_simengine_sim_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='day',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
