# Generated by Django 5.0.2 on 2024-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0059_flight_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='fuel_burn',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fuel burn (lbs/miles)'),
        ),
        migrations.AlterField(
            model_name='economy',
            name='gas_price',
            field=models.DecimalField(decimal_places=6, default=1.1, max_digits=10),
        ),
    ]
