# Generated by Django 5.0.2 on 2024-04-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0061_alter_fleet_aircraft_alter_fleet_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline_app.aircraft'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airline_app.airport'),
        ),
    ]
