# Generated by Django 5.0.2 on 2024-04-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0062_alter_fleet_aircraft_alter_fleet_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='next_a_check',
            field=models.PositiveIntegerField(default=70, verbose_name='Next A-Check (days)'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_b_check',
            field=models.PositiveIntegerField(default=280, verbose_name='Next B-Check (days)'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_c_check',
            field=models.PositiveIntegerField(default=560, verbose_name='Next C-Check (days)'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='next_d_check',
            field=models.PositiveIntegerField(default=2800, verbose_name='Next D-Check (days)'),
        ),
    ]
