# Generated by Django 5.0.2 on 2024-04-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0063_alter_fleet_next_a_check_alter_fleet_next_b_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.CharField(blank=True, max_length=7, verbose_name='Flight number'),
        ),
    ]
