# Generated by Django 5.0.2 on 2024-04-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0066_alter_flight_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='sch_arrival_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sch_departure_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
