# Generated by Django 5.0.2 on 2024-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0067_alter_flight_sch_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='act_arrival_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='act_departure_time',
            field=models.TimeField(blank=True),
        ),
    ]
