# Generated by Django 5.0.2 on 2024-04-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0068_alter_flight_act_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='sch_arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sch_departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
