# Generated by Django 5.0.2 on 2024-04-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0069_alter_flight_sch_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='act_arrival_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='act_departure_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
