# Generated by Django 5.0.2 on 2024-04-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0070_alter_flight_act_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
