# Generated by Django 5.0.2 on 2024-04-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0071_flight_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelled'),
        ),
    ]
