# Generated by Django 5.0.2 on 2024-04-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0073_remove_flight_is_cancelled_flight_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Cancel'),
        ),
    ]
