# Generated by Django 5.0.2 on 2024-04-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0075_alter_economy_gas_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='range',
            field=models.IntegerField(verbose_name='Range (miles)'),
        ),
    ]
