# Generated by Django 5.0.2 on 2024-04-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0078_alter_simengine_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simengine',
            old_name='sim_day',
            new_name='current_day',
        ),
    ]
