# Generated by Django 5.0.2 on 2024-04-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0079_rename_sim_day_simengine_current_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='current_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
