# Generated by Django 5.0.2 on 2024-04-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0081_alter_airline_homebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='airline',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
