# Generated by Django 5.0.2 on 2024-04-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0082_alter_airline_costs_alter_airline_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
