# Generated by Django 5.0.2 on 2024-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0084_flightcostmodel_flight_captains_onboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='captains_onboard',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flight',
            name='first_officers_onboard',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_attendants',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
