# Generated by Django 5.0.2 on 2024-04-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0085_alter_flight_captains_onboard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='captains_onboard',
            new_name='captains',
        ),
    ]
