# Generated by Django 5.0.2 on 2024-04-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0086_rename_captains_onboard_flight_captains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='first_officers_onboard',
            new_name='first_officers',
        ),
    ]
