# Generated by Django 5.0.2 on 2024-04-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0087_rename_first_officers_onboard_flight_first_officers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightCostModel',
            new_name='AirlineCostModel',
        ),
    ]
