# Generated by Django 5.0.2 on 2024-04-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0088_rename_flightcostmodel_airlinecostmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirlineCostModel',
            new_name='CostModel',
        ),
    ]
