# Generated by Django 5.0.2 on 2024-04-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0089_rename_airlinecostmodel_costmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostModel',
            new_name='AirlineCosts',
        ),
    ]
