# Generated by Django 5.0.2 on 2024-04-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0090_rename_costmodel_airlinecosts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirlineCosts',
            new_name='AirlineCost',
        ),
    ]
