# Generated by Django 5.0.2 on 2024-04-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0091_rename_airlinecosts_airlinecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='cost_model',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline_app.airlinecost'),
        ),
    ]
