# Generated by Django 5.0.2 on 2024-04-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0092_airline_cost_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
