# Generated by Django 5.0.2 on 2024-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0093_flight_crew_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
