# Generated by Django 5.0.2 on 2024-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0094_flight_fuel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
