# Generated by Django 5.0.2 on 2024-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0102_alter_fleet_is_active_alter_fleet_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='<br>Designates whether this fleet aircraft should be treated as active.\n        Uncheck instead of deleting aircarft.', verbose_name='Active'),
        ),
    ]
