# Generated by Django 5.0.2 on 2024-04-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0104_alter_fleet_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='initial_pax_demand',
            field=models.FloatField(default=400.0, verbose_name='Initial PAX demand'),
        ),
        migrations.AddField(
            model_name='economy',
            name='initial_ticket_price',
            field=models.FloatField(default=300.0, verbose_name='Initial ticket price ($/ticket)'),
        ),
        migrations.AlterField(
            model_name='economy',
            name='gas_price',
            field=models.FloatField(default=1.1, verbose_name='Gas Price ($/lb)'),
        ),
    ]
