# Generated by Django 5.0.2 on 2024-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0105_economy_initial_pax_demand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy',
            name='gas_price',
            field=models.DecimalField(decimal_places=4, default=1.1, max_digits=12, verbose_name='Gas Price ($/lb)'),
        ),
    ]
